rerun test2

diff --git a/.history/.github/workflows/tests_20250516151525.yml b/.history/.github/workflows/tests_20250516151525.yml
--- a/.history/.github/workflows/tests_20250516151525.yml
+++ b/.history/.github/workflows/tests_20250516151525.yml
@@ -28,20 +28,18 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
-      - name: Install Playwright browsers
+      - name: Install playwright browsers
         run: npx playwright install --with-deps
 
-      - name: Run initial tests and generate JSON report
-        run: |
-          QASE_MODE=testops npx playwright test --reporter=list,json,line > test-results.json || true
+      - name: Run tests
+        run: QASE_MODE=testops npx playwright test || true
 
-      - name: Check if JSON report was created
+      - name: Save JSON report
         run: |
           if [ -f test-results.json ]; then
             echo "JSON report exists"
           else
-            echo "test-results.json not found! Zkontroluj, že máš v configu reporter 'json'."
-            exit 1
+            echo "test-results.json not found, maybe no reporter?"
           fi
 
       - name: Extract failed test files
@@ -54,7 +52,7 @@ jobs:
           if [ -s failed-tests.txt ]; then
             echo "Retrying failed tests:"
             cat failed-tests.txt
-            xargs -a failed-tests.txt -I {} sh -c 'QASE_MODE=testops npx playwright test {}'
+            xargs -a failed-tests.txt npx playwright test
           else
             echo "No failed tests to retry."
           fi
@@ -65,3 +63,4 @@ jobs:
           name: playwright-report
           path: playwright-report/
           retention-days: 30
+
